In [1]:
import pandas as pd
import numpy as np

In [2]:
df_train = pd.read_csv('tcga_result/TCGA_drug_sensitivity_MixedSet_train.csv')
df_test = pd.read_csv('tcga_result/TCGA_drug_sensitivity_MixedSet_test.csv')
print(df_train.shape)
print(df_test.shape)
# Merge df_train and df_test
df_drug_sensitivity = pd.concat([df_train, df_test])
print(df_drug_sensitivity.shape)

(3013, 5)
(380, 5)
(3393, 5)

In [3]:
# Count the number of different values in the bcr_patient_barcode column; the number of different values in the drug column; the number of different values in the project column in df_drug_sensitivity.

print('patients',df_drug_sensitivity['bcr_patient_barcode'].nunique())
print('drugs',df_drug_sensitivity['drug'].nunique())
print('projects',df_drug_sensitivity['project'].nunique())

patients 1521
drugs 142
projects 30

In [5]:
df_drug_sensitivity = pd.read_csv('tcga_result/clinical_drug_merged_simplified.csv')
print(df_drug_sensitivity.shape)
df_drug_sensitivity.head()

(3812, 5)

,bcr_patient_barcode,drug_name,measure_of_response,Response,therapy_type
0,TCGA-KM-A7Q8,Sunitinib,Clinical Progressive Disease,0,Targeted Molecular therapy
1,TCGA-KN-8428,sorafenib,Clinical Progressive Disease,0,Targeted Molecular therapy
2,TCGA-KO-8404,Thalidomide,Clinical Progressive Disease,0,Chemotherapy
3,TCGA-UW-A7GR,Interferon,Partial Response,1,Immunotherapy
4,TCGA-UW-A7GR,Sorafenib,Partial Response,1,Chemotherapy

In [6]:
df_drug_smiles = pd.read_csv('tcga_result/TCGA_Drug_Name_SMILES.csv')[['CID','DRUG_NAME', 'Canonical_SMILES']]
print(df_drug_smiles.shape)
df_drug_smiles.head()

(297, 3)

,CID,DRUG_NAME,Canonical_SMILES
0,9854073,cabazitaxel,CC1=C2C(C(=O)C3(C(CC4C(C3C(C(C2(C)C)(CC1OC(=O)...
1,16136245,degarelix,CC(C)CC(C(=O)NC(CCCCNC(C)C)C(=O)N1CCCC1C(=O)NC...
2,5329102,SUTENT,CCN(CC)CCNC(=O)C1=C(NC(=C1C)C=C2C3=C(C=CC(=C3)...
3,74990,Irinotecan Hydrochloride,CCC1=C2CN3C(=CC4=C(C3=O)COC(=O)C4(CC)O)C2=NC5=...
4,11751549,Erythropoietin,CCCCC1=NC(=C(N1CC2=CC=C(C=C2)C3=CC=CC=C3C4=NN=...

In [7]:
# df_drug_sensitivity merged with df_drug_smiles based on the former drug_name column and the latter DRUG_NAME column

df_drug_sensitivity = pd.merge(df_drug_sensitivity, df_drug_smiles, left_on='drug_name', right_on='DRUG_NAME', how='left')
print(df_drug_sensitivity.shape)
df_drug_sensitivity.head()

(3812, 8)

,bcr_patient_barcode,drug_name,measure_of_response,Response,therapy_type,CID,DRUG_NAME,Canonical_SMILES
0,TCGA-KM-A7Q8,Sunitinib,Clinical Progressive Disease,0,Targeted Molecular therapy,5329102.0,Sunitinib,CCN(CC)CCNC(=O)C1=C(NC(=C1C)C=C2C3=C(C=CC(=C3)...
1,TCGA-KN-8428,sorafenib,Clinical Progressive Disease,0,Targeted Molecular therapy,216239.0,sorafenib,CNC(=O)C1=NC=CC(=C1)OC2=CC=C(C=C2)NC(=O)NC3=CC...
2,TCGA-KO-8404,Thalidomide,Clinical Progressive Disease,0,Chemotherapy,5426.0,Thalidomide,C1CC(=O)NC(=O)C1N2C(=O)C3=CC=CC=C3C2=O
3,TCGA-UW-A7GR,Interferon,Partial Response,1,Immunotherapy,NaN,NaN,NaN
4,TCGA-UW-A7GR,Sorafenib,Partial Response,1,Chemotherapy,216239.0,Sorafenib,CNC(=O)C1=NC=CC(=C1)OC2=CC=C(C=C2)NC(=O)NC3=CC...

In [8]:
# tocsv
# df_drug_sensitivity.to_csv('tcga_result/TCGA_drug_sensitivity.csv', index=False)

## read TCGA drug sensitivity data

In [9]:
df_drug_sensitivity = pd.read_csv('tcga_result/TCGA_drug_sensitivity.csv')
print(df_drug_sensitivity.shape)
df_drug_sensitivity.head()

(3484, 8)

,bcr_patient_barcode,drug_name,measure_of_response,Response,therapy_type,CID,DRUG_NAME,Canonical_SMILES
0,TCGA-KM-A7Q8,Sunitinib,Clinical Progressive Disease,0,Targeted Molecular therapy,5329102,Sunitinib,CCN(CC)CCNC(=O)C1=C(NC(=C1C)C=C2C3=C(C=CC(=C3)...
1,TCGA-KN-8428,sorafenib,Clinical Progressive Disease,0,Targeted Molecular therapy,216239,sorafenib,CNC(=O)C1=NC=CC(=C1)OC2=CC=C(C=C2)NC(=O)NC3=CC...
2,TCGA-KO-8404,Thalidomide,Clinical Progressive Disease,0,Chemotherapy,5426,Thalidomide,C1CC(=O)NC(=O)C1N2C(=O)C3=CC=CC=C3C2=O
3,TCGA-UW-A7GR,Sorafenib,Partial Response,1,Chemotherapy,216239,Sorafenib,CNC(=O)C1=NC=CC(=C1)OC2=CC=C(C=C2)NC(=O)NC3=CC...
4,TCGA-13-A5FT,Cisplatin,Complete Response,1,Chemotherapy,5702198,Cisplatin,N.N.Cl[Pt]Cl

In [10]:
# df_drug_sensitivity Group the DRUG_NAMEs according to the CID column, count the number of different DRUG_NAMEs in each group, and change all the DRUG_NAMEs to the one with the most occurrences.

df_drug_sensitivity['DRUG_NAME'] = df_drug_sensitivity.groupby('CID')['DRUG_NAME'].transform(lambda x: x.value_counts().index[0])
# df_drug_sensitivity = df_drug_sensitivity.drop_duplicates()
print(df_drug_sensitivity.shape)
df_drug_sensitivity.head()

(3484, 8)

,bcr_patient_barcode,drug_name,measure_of_response,Response,therapy_type,CID,DRUG_NAME,Canonical_SMILES
0,TCGA-KM-A7Q8,Sunitinib,Clinical Progressive Disease,0,Targeted Molecular therapy,5329102,Sutent,CCN(CC)CCNC(=O)C1=C(NC(=C1C)C=C2C3=C(C=CC(=C3)...
1,TCGA-KN-8428,sorafenib,Clinical Progressive Disease,0,Targeted Molecular therapy,216239,Sorafenib,CNC(=O)C1=NC=CC(=C1)OC2=CC=C(C=C2)NC(=O)NC3=CC...
2,TCGA-KO-8404,Thalidomide,Clinical Progressive Disease,0,Chemotherapy,5426,Thalidomide,C1CC(=O)NC(=O)C1N2C(=O)C3=CC=CC=C3C2=O
3,TCGA-UW-A7GR,Sorafenib,Partial Response,1,Chemotherapy,216239,Sorafenib,CNC(=O)C1=NC=CC(=C1)OC2=CC=C(C=C2)NC(=O)NC3=CC...
4,TCGA-13-A5FT,Cisplatin,Complete Response,1,Chemotherapy,5702198,Cisplatin,N.N.Cl[Pt]Cl

In [11]:
# Count the number of different values in the bcr_patient_barcode column; count the number of different values in the drug_name column.
print('patients',df_drug_sensitivity['bcr_patient_barcode'].nunique())
print('drugs',df_drug_sensitivity['DRUG_NAME'].nunique())

patients 1572
drugs 145

In [12]:
# tocsv
# df_drug_sensitivity.to_csv('tcga_result/TCGA_drug_sensitivity_filtered.csv', index=False)

## TCGA drug sensitivity data -> SMILES DATA

In [13]:
# Extract the DRUG_NAME and Canonical_SMILES columns from df_drug_sensitivity, de-duplicated
df_drug_smiles = df_drug_sensitivity[['CID','DRUG_NAME', 'Canonical_SMILES']].drop_duplicates()
# Sorted by DRUG_NAME columns
df_drug_smiles = df_drug_smiles.sort_values(by='DRUG_NAME')
print(df_drug_smiles.shape)
df_drug_smiles.head()

(145, 3)

,CID,DRUG_NAME,Canonical_SMILES
113,3385,5-Fluorouracil,C1=C(C(=O)NC(=O)N1)F
723,45480520,ABT-888,CC1(CCCN1)C2=NC3=C(C=CC=C3N2)C(=O)N.Cl.Cl
2373,10127622,AZD6244,CN1C=NC2=C1C=C(C(=C2F)NC3=C(C=C(C=C3)Br)Cl)C(=...
1862,457193,Actinomycin-D,CC1C(C(=O)NC(C(=O)N2CCCC2C(=O)N(CC(=O)N(C(C(=O...
10,31703,Adriamycin,CC1C(C(CC(O1)OC2CC(CC3=C2C(=C4C(=C3O)C(=O)C5=C...

In [14]:
# tocsv 
# df_drug_smiles.to_csv('tcga_result/TCGA_drug_smiles.csv', index=False,header=True)

## calculate patient

In [16]:
df_clinical = pd.read_csv('tcga_result/clinical_patient_merged_simplified.csv')
print(df_clinical.shape)
df_clinical.head()

(11076, 10)

,bcr_patient_barcode,vital_status,days_to_last_followup,days_to_death,OS,gender,pathologic_stage,age_at_initial_pathologic_diagnosis,cancer_type,project
0,TCGA-3M-AB46,Alive,1703,[Not Applicable],1703,MALE,Stage IB,70,0089d221-5807-47f1-a382-1e2e336df201,TCGA-STAD
1,TCGA-B7-5816,Alive,171,[Not Applicable],171,FEMALE,Stage IIB,51,0089d221-5807-47f1-a382-1e2e336df201,TCGA-STAD
2,TCGA-B7-5818,Alive,3,[Not Applicable],3,MALE,Stage IB,62,0089d221-5807-47f1-a382-1e2e336df201,TCGA-STAD
3,TCGA-B7-A5TI,Alive,230,[Not Applicable],230,MALE,Stage IIIC,52,0089d221-5807-47f1-a382-1e2e336df201,TCGA-STAD
4,TCGA-B7-A5TJ,Alive,25,[Not Applicable],25,MALE,Stage IIB,74,0089d221-5807-47f1-a382-1e2e336df201,TCGA-STAD

In [17]:
# of bcr_patient_barcode columns in df_drug_sensitivity that intersect with bcr_patient_barcode in df_clinical
print('patients in drug sensitivity',df_drug_sensitivity['bcr_patient_barcode'].nunique())
print('patients in clinical',df_clinical['bcr_patient_barcode'].nunique())
print('patients in both',len(set(df_drug_sensitivity['bcr_patient_barcode']) & set(df_clinical['bcr_patient_barcode'])))

patients in drug sensitivity 1572
patients in clinical 11076
patients in both 1569

## drug sensitivity data -> addition of CancerType/project

In [22]:
df_clinical = pd.read_csv('tcga_result/TCGA_clinical.csv')[['bcr_patient_barcode','project']]
df_clinical = df_clinical.drop_duplicates()
print(df_clinical.shape)
df_clinical.head()

(11076, 2)

  bcr_patient_barcode    project
0        TCGA-3M-AB46  TCGA-STAD
1        TCGA-B7-5816  TCGA-STAD
2        TCGA-B7-5818  TCGA-STAD
3        TCGA-B7-A5TI  TCGA-STAD
4        TCGA-B7-A5TJ  TCGA-STAD

In [23]:
df_drug_sensitivity = pd.read_csv('tcga_result/TCGA_drug_sensitivity.csv')
print(df_drug_sensitivity.shape)
df_drug_sensitivity.head()

(3484, 9)

,drug,bcr_patient_barcode,response,drug_name_raw,measure_of_response,therapy_type,CID,Canonical_SMILES,project
0,Sutent,TCGA-KM-A7Q8,0,Sunitinib,Clinical Progressive Disease,Targeted Molecular therapy,5329102,CCN(CC)CCNC(=O)C1=C(NC(=C1C)C=C2C3=C(C=CC(=C3)...,TCGA-KICH
1,Sorafenib,TCGA-KN-8428,0,sorafenib,Clinical Progressive Disease,Targeted Molecular therapy,216239,CNC(=O)C1=NC=CC(=C1)OC2=CC=C(C=C2)NC(=O)NC3=CC...,TCGA-KICH
2,Thalidomide,TCGA-KO-8404,0,Thalidomide,Clinical Progressive Disease,Chemotherapy,5426,C1CC(=O)NC(=O)C1N2C(=O)C3=CC=CC=C3C2=O,TCGA-KICH
3,Sorafenib,TCGA-UW-A7GR,1,Sorafenib,Partial Response,Chemotherapy,216239,CNC(=O)C1=NC=CC(=C1)OC2=CC=C(C=C2)NC(=O)NC3=CC...,TCGA-KICH
4,Cisplatin,TCGA-13-A5FT,1,Cisplatin,Complete Response,Chemotherapy,5702198,N.N.Cl[Pt]Cl,TCGA-OV

In [12]:
# df_drug_sensitivity is merged with df_clinical, based on the former bcr_patient_barcode column and the latter bcr_patient_barcode column.
df_drug_sensitivity = pd.merge(df_drug_sensitivity, df_clinical, on='bcr_patient_barcode', how='left')
print(df_drug_sensitivity.shape)
df_drug_sensitivity.head()

(3484, 9)

,drug,bcr_patient_barcode,response,drug_name_raw,measure_of_response,therapy_type,CID,Canonical_SMILES,project
0,Sutent,TCGA-KM-A7Q8,0,Sunitinib,Clinical Progressive Disease,Targeted Molecular therapy,5329102,CCN(CC)CCNC(=O)C1=C(NC(=C1C)C=C2C3=C(C=CC(=C3)...,TCGA-KICH
1,Sorafenib,TCGA-KN-8428,0,sorafenib,Clinical Progressive Disease,Targeted Molecular therapy,216239,CNC(=O)C1=NC=CC(=C1)OC2=CC=C(C=C2)NC(=O)NC3=CC...,TCGA-KICH
2,Thalidomide,TCGA-KO-8404,0,Thalidomide,Clinical Progressive Disease,Chemotherapy,5426,C1CC(=O)NC(=O)C1N2C(=O)C3=CC=CC=C3C2=O,TCGA-KICH
3,Sorafenib,TCGA-UW-A7GR,1,Sorafenib,Partial Response,Chemotherapy,216239,CNC(=O)C1=NC=CC(=C1)OC2=CC=C(C=C2)NC(=O)NC3=CC...,TCGA-KICH
4,Cisplatin,TCGA-13-A5FT,1,Cisplatin,Complete Response,Chemotherapy,5702198,N.N.Cl[Pt]Cl,TCGA-OV

In [13]:
# tocsv
# df_drug_sensitivity.to_csv('tcga_result/TCGA_drug_sensitivity_with_project.csv', index=False)

In [12]:
df_drug_sensitivity_all = pd.read_csv('tcga_result/TCGA_drug_sensitivity.csv')[['drug','bcr_patient_barcode','response','measure_of_response']]
print(df_drug_sensitivity_all.shape)
df_drug_sensitivity_all.head()

(3484, 4)

          drug bcr_patient_barcode  response           measure_of_response
0       Sutent        TCGA-KM-A7Q8         0  Clinical Progressive Disease
1    Sorafenib        TCGA-KN-8428         0  Clinical Progressive Disease
2  Thalidomide        TCGA-KO-8404         0  Clinical Progressive Disease
3    Sorafenib        TCGA-UW-A7GR         1              Partial Response
4    Cisplatin        TCGA-13-A5FT         1             Complete Response

In [3]:
df_drug_sensitivity_train = pd.read_csv('tcga_result/TCGA_drug_sensitivity_MixedSet_train.csv',index_col=0)
df_drug_sensitivity_test = pd.read_csv('tcga_result/TCGA_drug_sensitivity_MixedSet_test.csv',index_col=0)
print(df_drug_sensitivity_train.shape)
print(df_drug_sensitivity_test.shape)

(3013, 4)
(380, 4)

In [13]:
df_predictions = pd.read_csv('tcga_result/TCGA_drug_sensitivity_MixedSet_predictions.csv')
print(df_predictions.shape)

(380, 7)

In [14]:
# Merge df_drug_sensitivity_train, df_drug_sensitivity_test and df_drug_sensitivity_all based on drug and bcr_patient_barcode columns
df_predictions = pd.merge(df_predictions, df_drug_sensitivity_all, on=['drug','bcr_patient_barcode','response'], how='left')
print(df_predictions.shape)
df_predictions = df_predictions.drop_duplicates()
print(df_predictions.shape)
df_predictions.head()

(412, 8)
(384, 8)

,bcr_patient_barcode,drug,response,project,predict,predict0,predict1,measure_of_response
0,TCGA-N8-A4PN,Carboplatin,1,TCGA-UCS,1,0.218275,0.781725,Complete Response
1,TCGA-NC-A5HQ,Vinorelbine,1,TCGA-LUSC,1,0.000418,0.999582,Complete Response
2,TCGA-DU-A7TB,Temodar,1,TCGA-LGG,1,0.322660,0.677340,Stable Disease
4,TCGA-HT-7604,Temodar,1,TCGA-LGG,1,0.426555,0.573445,Partial Response
5,TCGA-VS-A9UY,Cisplatin,0,TCGA-CESC,1,0.026309,0.973691,Clinical Progressive Disease

In [15]:
# tocsv
df_predictions.to_csv('tcga_result/TCGA_drug_sensitivity_MixedSet_predictions_with_response.csv', index=False)

In [9]:
df_gep_bcr_patient_barcode = pd.read_csv('tcga_result/TCGA_GEP_Wilcoxon_Test_Analysis_Log10_P_value_C2_KEGG_MEDICUS.csv')[['bcr_patient_barcode']]
print(df_gep_bcr_patient_barcode.shape)
df_gep_bcr_patient_barcode.head()

(1638, 1)

  bcr_patient_barcode
0        TCGA-90-A4EE
1        TCGA-KT-A74X
2        TCGA-HT-8013
3        TCGA-BG-A0VZ
4        TCGA-X6-A8C6

In [10]:
# Filter out rows from df_drug_sensitivity_train where the bcr_patient_barcode column does not exist in the bcr_patient_barcode column of df_gep_bcr_patient_barcode.
df_drug_sensitivity_train = df_drug_sensitivity_train[~df_drug_sensitivity_train['bcr_patient_barcode'].isin(df_gep_bcr_patient_barcode['bcr_patient_barcode'])]
print(df_drug_sensitivity_train.shape)
df_drug_sensitivity_train.head()

(83, 4)

           drug bcr_patient_barcode  response    project
0      Taxotere        TCGA-K1-A3PN         0  TCGA-SARC
99   Leucovorin        TCGA-AA-3967         1  TCGA-COAD
137   Lomustine        TCGA-26-A7UX         1   TCGA-GBM
142  Adriamycin        TCGA-C8-A9FZ         1  TCGA-BRCA
148   Cisplatin        TCGA-BT-A42B         0  TCGA-BLCA

In [11]:
# Filter out the rows in df_drug_sensitivity_test where the bcr_patient_barcode column does not exist in the bcr_patient_barcode column of df_gep.
df_drug_sensitivity_test = df_drug_sensitivity_test[~df_drug_sensitivity_test['bcr_patient_barcode'].isin(df_gep_bcr_patient_barcode['bcr_patient_barcode'])]
print(df_drug_sensitivity_test.shape)
df_drug_sensitivity_test.head()

(8, 4)

            drug bcr_patient_barcode  response    project
50   Oxaliplatin        TCGA-NH-A8F7         1  TCGA-COAD
71       Temodar        TCGA-06-A5U0         0   TCGA-GBM
90        Gemzar        TCGA-FZ-5924         0  TCGA-PAAD
154  Gemcitabine        TCGA-BT-A42B         0  TCGA-BLCA
211      Temodar        TCGA-06-A7TL         1   TCGA-GBM

In [13]:
# Merge df_drug_sensitivity_train and df_drug_sensitivity_test.
df_drug_sensitivity = pd.concat([df_drug_sensitivity_train, df_drug_sensitivity_test])[['bcr_patient_barcode']]
print(df_drug_sensitivity.shape)
df_drug_sensitivity.head()

(91, 1)

    bcr_patient_barcode
0          TCGA-K1-A3PN
99         TCGA-AA-3967
137        TCGA-26-A7UX
142        TCGA-C8-A9FZ
148        TCGA-BT-A42B

In [14]:
# Remove duplicates.
df_drug_sensitivity = df_drug_sensitivity.drop_duplicates()
print(df_drug_sensitivity.shape)
df_drug_sensitivity.head()

(51, 1)

    bcr_patient_barcode
0          TCGA-K1-A3PN
99         TCGA-AA-3967
137        TCGA-26-A7UX
142        TCGA-C8-A9FZ
148        TCGA-BT-A42B

In [16]:
# 去除df_drug_sensitivity_train和df_drug_sensitivity_test中bcr_patient_barcode列与df_drug_sensitivity中bcr_patient_barcode存在的行
df_drug_sensitivity_train = df_drug_sensitivity_train[~df_drug_sensitivity_train['bcr_patient_barcode'].isin(df_drug_sensitivity['bcr_patient_barcode'])]
df_drug_sensitivity_test = df_drug_sensitivity_test[~df_drug_sensitivity_test['bcr_patient_barcode'].isin(df_drug_sensitivity['bcr_patient_barcode'])]
print(df_drug_sensitivity_train.shape)
print(df_drug_sensitivity_test.shape)

(3013, 4)
(380, 4)

In [17]:
# tocsv
df_drug_sensitivity_train.to_csv('tcga_result/TCGA_drug_sensitivity_MixedSet_train.csv', index=False)
df_drug_sensitivity_test.to_csv('tcga_result/TCGA_drug_sensitivity_MixedSet_test.csv', index=False)

In [21]:
# Merge df_drug_sensitivity_train and df_drug_sensitivity_test.
df_drug_sensitivity = pd.concat([df_drug_sensitivity_train, df_drug_sensitivity_test])
print(df_drug_sensitivity.shape)
df_drug_sensitivity.head()

(3393, 4)

          drug bcr_patient_barcode  response    project
1      cytomel        TCGA-KS-A4IC         1  TCGA-THCA
2  Dacarbazine        TCGA-X9-A973         1  TCGA-SARC
3   Adriamycin        TCGA-E9-A1NI         1  TCGA-BRCA
4   Adriamycin        TCGA-KD-A5QS         1  TCGA-SARC
5  Vinorelbine        TCGA-18-3415         1  TCGA-LUSC

In [23]:
# Count the number of patients, drugs, and projects.
print('patients',df_drug_sensitivity['bcr_patient_barcode'].nunique())
print('drugs',df_drug_sensitivity['drug'].nunique())
print('projects',df_drug_sensitivity['project'].nunique())

patients 1521
drugs 142
projects 30

In [26]:
# Sort by drug and bcr_patient_barcode, then reset the index.
df_drug_sensitivity = df_drug_sensitivity.sort_values(by=['bcr_patient_barcode'])
df_drug_sensitivity = df_drug_sensitivity.reset_index(drop=True)
df_drug_sensitivity.to_csv('tcga_result/TCGA_drug_sensitivity_filtered.csv', index=False)

In [25]:
df_template = df_drug_sensitivity[['drug','bcr_patient_barcode','project']]
print(df_template.shape)
df_template.head()

(3484, 3)

          drug bcr_patient_barcode    project
0       Sutent        TCGA-KM-A7Q8  TCGA-KICH
1    Sorafenib        TCGA-KN-8428  TCGA-KICH
2  Thalidomide        TCGA-KO-8404  TCGA-KICH
3    Sorafenib        TCGA-UW-A7GR  TCGA-KICH
4    Cisplatin        TCGA-13-A5FT    TCGA-OV